/* eslint-disable no-unused-vars */
import React, { useEffect } from 'react';

// Load pptxgenjs from CDN
const loadPptxGen = () => new Promise((resolve) => {
  if (window.PptxGenJS) { resolve(window.PptxGenJS); return; }
  const script = document.createElement('script');
  script.src = 'https://cdn.jsdelivr.net/npm/pptxgenjs@3.12.0/dist/pptxgen.bundle.js';
  script.onload = () => resolve(window.PptxGenJS);
  document.head.appendChild(script);
});

// Load jsPDF from CDN
const loadJsPDF = () => new Promise((resolve) => {
  if (window.jspdf) { resolve(window.jspdf.jsPDF); return; }
  const script = document.createElement('script');
  script.src = 'https://cdn.jsdelivr.net/npm/jspdf@2.5.1/dist/jspdf.umd.min.js';
  script.onload = () => resolve(window.jspdf.jsPDF);
  document.head.appendChild(script);
});

export const generatePptx = async (data) => {
  const PptxGenJS = await loadPptxGen();
  const prs = new PptxGenJS();

  prs.layout = 'LAYOUT_WIDE';
  prs.author = 'Melius AI';
  prs.title = data.title || 'Melius Presentation';

  const GOLD = 'C9A84C';
  const INK = '0E0E0E';
  const PAPER = 'FAFAF8';
  const MUTED = '787878';

  // Title slide
  const titleSlide = prs.addSlide();
  titleSlide.background = { color: INK };

  // Gold accent line
  titleSlide.addShape(prs.ShapeType.rect, {
    x: 0.5, y: 3.2, w: 1.5, h: 0.04,
    fill: { color: GOLD },
    line: { type: 'none' },
  });

  titleSlide.addText(data.title || 'Presentation', {
    x: 0.5, y: 1.8, w: 8.5, h: 1.2,
    fontSize: 44,
    fontFace: 'Georgia',
    color: PAPER,
    bold: false,
    italic: true,
  });

  if (data.subtitle) {
    titleSlide.addText(data.subtitle, {
      x: 0.5, y: 3.4, w: 7, h: 0.6,
      fontSize: 18,
      fontFace: 'Calibri',
      color: MUTED,
    });
  }

  titleSlide.addText('Generated by Melius AI', {
    x: 0.5, y: 6.8, w: 4, h: 0.3,
    fontSize: 10,
    fontFace: 'Calibri',
    color: GOLD,
    italic: true,
  });

  // Content slides
  (data.slides || []).forEach((slide, idx) => {
    const s = prs.addSlide();
    s.background = { color: PAPER };

    // Slide number dot
    s.addShape(prs.ShapeType.ellipse, {
      x: 9.0, y: 0.2, w: 0.25, h: 0.25,
      fill: { color: GOLD },
      line: { type: 'none' },
    });

    // Title
    s.addText(slide.title || `Slide ${idx + 2}`, {
      x: 0.5, y: 0.35, w: 8.3, h: 0.7,
      fontSize: 28,
      fontFace: 'Georgia',
      color: INK,
      italic: true,
      bold: false,
    });

    // Gold underline
    s.addShape(prs.ShapeType.rect, {
      x: 0.5, y: 1.05, w: 9.0, h: 0.025,
      fill: { color: 'E8E6E0' },
      line: { type: 'none' },
    });

    // Content
    if (slide.points && slide.points.length > 0) {
      const rows = slide.points.map(point => [{
        text: point,
        options: {
          fontSize: 16,
          fontFace: 'Calibri',
          color: '3A3A3A',
          paraSpaceBefore: 8,
        }
      }]);

      slide.points.forEach((point, pi) => {
        s.addShape(prs.ShapeType.ellipse, {
          x: 0.5, y: 1.35 + (pi * 0.7), w: 0.12, h: 0.12,
          fill: { color: GOLD },
          line: { type: 'none' },
        });
        s.addText(point, {
          x: 0.75, y: 1.28 + (pi * 0.7), w: 8.5, h: 0.55,
          fontSize: 15,
          fontFace: 'Calibri',
          color: '3A3A3A',
          valign: 'middle',
        });
      });
    } else if (slide.content) {
      s.addText(slide.content, {
        x: 0.5, y: 1.25, w: 9.0, h: 4.5,
        fontSize: 16,
        fontFace: 'Calibri',
        color: '3A3A3A',
        valign: 'top',
        wrap: true,
      });
    }

    // Slide number bottom right
    s.addText(`${idx + 2}`, {
      x: 8.8, y: 6.8, w: 0.5, h: 0.25,
      fontSize: 10,
      fontFace: 'Calibri',
      color: MUTED,
      align: 'right',
    });
  });

  // Thank you / end slide
  const endSlide = prs.addSlide();
  endSlide.background = { color: INK };
  endSlide.addText('Thank you.', {
    x: 0.5, y: 2.8, w: 9, h: 1.2,
    fontSize: 48,
    fontFace: 'Georgia',
    color: PAPER,
    italic: true,
    align: 'center',
  });
  endSlide.addShape(prs.ShapeType.rect, {
    x: 3.5, y: 3.9, w: 3, h: 0.04,
    fill: { color: GOLD },
    line: { type: 'none' },
  });
  endSlide.addText('Generated by Melius AI', {
    x: 0.5, y: 6.8, w: 9, h: 0.3,
    fontSize: 10,
    fontFace: 'Calibri',
    color: GOLD,
    italic: true,
    align: 'center',
  });

  const filename = `${(data.title || 'melius-presentation').toLowerCase().replace(/\s+/g, '-')}.pptx`;
  await prs.writeFile({ fileName: filename });
  return filename;
};

export const generatePdf = async (data) => {
  const JsPDF = await loadJsPDF();
  const doc = new JsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  const GOLD = [201, 168, 76];
  const INK = [14, 14, 14];
  const MUTED = [120, 120, 120];
  const W = 210;
  const MARGIN = 20;

  let y = 0;

  const addPage = () => {
    doc.addPage();
    y = MARGIN;
  };

  const checkY = (needed = 20) => {
    if (y + needed > 270) addPage();
  };

  // Title page
  doc.setFillColor(...INK);
  doc.rect(0, 0, W, 297, 'F');

  // Gold accent
  doc.setFillColor(...GOLD);
  doc.rect(MARGIN, 120, 40, 1, 'F');

  doc.setTextColor(250, 250, 248);
  doc.setFont('times', 'italic');
  doc.setFontSize(36);
  doc.text(data.title || 'Document', MARGIN, 100);

  if (data.subtitle) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(14);
    doc.setTextColor(...MUTED);
    doc.text(data.subtitle, MARGIN, 128);
  }

  doc.setFont('helvetica', 'italic');
  doc.setFontSize(9);
  doc.setTextColor(...GOLD);
  doc.text('Generated by Melius AI', MARGIN, 280);

  // Content pages
  (data.slides || data.sections || []).forEach((section) => {
    addPage();

    // Section title
    doc.setFillColor(250, 250, 248);
    doc.rect(0, 0, W, 297, 'F');

    // Gold top bar
    doc.setFillColor(...GOLD);
    doc.rect(MARGIN, y, W - (MARGIN * 2), 0.5, 'F');
    y += 6;

    doc.setFont('times', 'italic');
    doc.setFontSize(22);
    doc.setTextColor(...INK);
    doc.text(section.title || '', MARGIN, y);
    y += 12;

    // Divider
    doc.setDrawColor(220, 218, 212);
    doc.setLineWidth(0.3);
    doc.line(MARGIN, y, W - MARGIN, y);
    y += 10;

    // Points or content
    if (section.points && section.points.length > 0) {
      section.points.forEach(point => {
        checkY(12);
        doc.setFillColor(...GOLD);
        doc.circle(MARGIN + 2, y - 2, 1.2, 'F');
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(12);
        doc.setTextColor(58, 58, 58);
        const lines = doc.splitTextToSize(point, W - MARGIN * 2 - 8);
        doc.text(lines, MARGIN + 7, y);
        y += (lines.length * 6) + 4;
      });
    } else if (section.content) {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(12);
      doc.setTextColor(58, 58, 58);
      const lines = doc.splitTextToSize(section.content, W - MARGIN * 2);
      lines.forEach(line => {
        checkY(8);
        doc.text(line, MARGIN, y);
        y += 7;
      });
    }

    // Page number
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(...MUTED);
    doc.text(`${doc.internal.getNumberOfPages()}`, W - MARGIN, 285, { align: 'right' });
  });

  const filename = `${(data.title || 'melius-document').toLowerCase().replace(/\s+/g, '-')}.pdf`;
  doc.save(filename);
  return filename;
};

export default { generatePptx, generatePdf };